spring:
  jpa:
    show_sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db_classify?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 5001
  servlet:
    context-path: /api
security:
  basic:
    enable: false
  oauth2:
    resource:
      token-info-uri: http://localhost:5002/auth/oauth/check_token
    client:
      client-id: demo
      client-secret: demo
